/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/Metro.glb -o src/components/Metro.jsx 
*/

import React, { useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import * as THREE from 'three';

export function Metro({ onLoaded, ...props }) {
  const group = React.useRef();
  const { nodes, materials, animations, scene } = useGLTF('/assets/models/Metro.glb');
  const { actions, mixer } = useAnimations(animations, group);

  // 외부에서 액션, mixer 접근 가능하게 전달 + 반복 없이 재생 설정
  useEffect(() => {
    if (onLoaded && group.current) {
      // 애니메이션 반복 없이 설정
      Object.values(actions).forEach((action) => {
        action.setLoop(THREE.LoopOnce, 1);
        action.clampWhenFinished = true;
      });
      onLoaded({ ref: group.current, mixer, actions });
    }
  }, [onLoaded, mixer, actions]);

  // 모든 mesh에 castShadow 적용
  useEffect(() => {
    if (group.current) {
      group.current.traverse((child) => {
        if (child.isMesh) child.castShadow = true;
      });
    }
  }, []);

  return (
    <group ref={group} {...props} dispose={null}  scale={[1.5, 1.5, 1.5]} >
      <group name="Scene">
        <group name="gamsoong" />
        <group name="Empty" position={[-15.695, -2.238, 0.98]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.726}>
          <group name="Cube005" position={[-0.139, 0, -0.555]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.579, 0.579, 0.538]}>
            <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Material.001']} />
            <mesh name="Cube008_1" geometry={nodes.Cube008_1.geometry} material={materials['Material.002']} />
            <mesh name="Cube008_2" geometry={nodes.Cube008_2.geometry} material={materials.Material} />
            <mesh name="Cube008_3" geometry={nodes.Cube008_3.geometry} material={materials['Material.004']} />
            <mesh name="Cube008_4" geometry={nodes.Cube008_4.geometry} material={materials['Material.003']} />
          </group>
        </group>
        <group name="Empty002" position={[-15.695, -2.241, 4.602]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <group name="Cube002" position={[-0.019, 0, -1.494]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.928]}>
            <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.001']} />
            <mesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={materials['Material.002']} />
            <mesh name="Cube006_2" geometry={nodes.Cube006_2.geometry} material={materials.Material} />
            <mesh name="Cube006_3" geometry={nodes.Cube006_3.geometry} material={materials['Material.004']} />
            <mesh name="Cube006_4" geometry={nodes.Cube006_4.geometry} material={materials['Material.003']} />
          </group>
        </group>
        <group name="KakaoTalk_20250301_145139734" position={[0, -2.305, 0]} rotation={[0, Math.PI / 2, 0]} scale={[-40, -31.563, -40]}>
          <mesh name="KakaoTalk_20250301_145139734_1" geometry={nodes.KakaoTalk_20250301_145139734_1.geometry} material={materials.KakaoTalk_20250301_145139734} />
          <mesh name="KakaoTalk_20250301_145139734_2" geometry={nodes.KakaoTalk_20250301_145139734_2.geometry} material={materials['Material.003']} />
        </group>
        <group name="Cube" position={[15.765, 3.188, -7.037]} scale={[0.01, 0.01, 0.021]}>
          <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials['Material.024']} />
          <mesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials['Material.025']} />
          <mesh name="Cube_3" geometry={nodes.Cube_3.geometry} material={materials['Material.026']} />
          <mesh name="KakaoTalk_20250306_170635956" geometry={nodes.KakaoTalk_20250306_170635956.geometry} material={materials.KakaoTalk_20250306_170635956} position={[1.005, 1.247, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.123, 2.398, 2.19]} />
        </group>
        <group name="Cube001" position={[16.231, 1.262, -12.268]} scale={0.01}>
          <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['Material.028']} />
          <mesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials['Material.027']} />
          <mesh name="Cube002_3" geometry={nodes.Cube002_3.geometry} material={materials['Material.029']} />
          <mesh name="Cube002_4" geometry={nodes.Cube002_4.geometry} material={materials['Material.030']} />
        </group>
        <group name="Cube004" position={[18.298, 1.454, -15.675]} scale={0.013}>
          <mesh name="Cube004_1" geometry={nodes.Cube004_1.geometry} material={materials['Material.026']} />
          <mesh name="Cube004_2" geometry={nodes.Cube004_2.geometry} material={materials['Material.044']} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/assets/models/Metro.glb');
